canvas = undefined

setup = ->
  canvas = createCanvas windowWidth, windowHeight, WEBGL
  canvas.parent "#hero-animation"
  return

draw = ->
  background 200
  stroke(245, 244, 236)
  noFill()

  beginShape(TRIANGLE_STRIP)
  vertex(30, 20, 1)
  vertex(851, 20, 45)
  vertex(85, 75, 12)
  vertex(130, 735, 0)
  endShape(CLOSE)
  return

# ---
# generated by js2coffee 2.2.0
